# -*- coding: utf-8 -*-
# vim: ft=yaml
---
kubernetes:
  div: '/'
  clean: false
  overwrite: true   # for archive.extracted on windows
  formula: kubernetes
  supported:
    - server
    - client
    - node
    - k3s
    - operator
    - operators
    - devlibs
    - devtools
    - sigs
  sigs:
    wanted:
      - kind
      - krew
      - kubebuilder
    pkg:
      kind:
        version: '0.9.0'
        commands:
          - kind
        use_upstream: binary
        uri_b: 'https://github.com/kubernetes-sigs/kind/releases/download'
        binary:
          source_hash: '35a640e0ca479192d86a51b6fd31c657403d2cf7338368d62223938771500dc8'
      krew:
        version: '0.4.0'
        commands:
          - krew-linux_amd64
        use_upstream: archive
        uri_a: 'https://github.com/kubernetes-sigs/krew/releases/download'
        archive:
          options: '--strip-components=1'
        suffix: tar.gz
      kubebuilder:
        version: '2.3.1'
        commands:
          # etcd
          # kube-apiserver
          - kubebuilder
          # kubectl
        use_upstream: archive
        uri_a: 'https://github.com/kubernetes-sigs/kubebuilder/releases/download'
        archive:
          source_hash: 'ff496970f209706763f2aba2bdcefc2de8d00085b3b972b5790117b59ea4ed10'
          options: '--strip-components=1'
        suffix: tar.gz

  devtools:
    wanted:
      - audit2rbac
      - cue
      - devspace
      - dive
      - istio
      - kubectx
      - kubens
      - kudo
      - linkerd2
      - minikube
      - octant
      - skaffold
      - stern
    pkg:
      devspace:
        version: 5.6.2
        commands:
          - devspace
        use_upstream: binary
        uri_b: 'https://github.com/devspace-cloud/devspace/releases/download'
        binary: {}  # needed
        suffix: null
      octant:
        version: '0.16.3'
        commands:
          - octant
        use_upstream: archive
        uri_a: 'https://github.com/vmware-tanzu/octant/releases/download'
        archive:
          source_hash: '1df88ddf8990a85fd8182c25687249eab718ac2356e60f9618932412513bdbb0'  # 64Bit
          options: '--strip-components=1'
        suffix: tar.gz
      linkerd2:
        version: 20.12.3
        commands:
          - linkerd2
        use_upstream: binary
        uri_b: 'https://github.com/linkerd/linkerd2/releases/download'
        binary: {}  # needed
        suffix: ''
      skaffold:
        version: 1.17.2
        commands:
          - skaffold
        use_upstream: binary
        uri_b: 'https://storage.googleapis.com/skaffold/releases'
        binary: {}  # needed
        suffix: ''
      istio:
        version: 1.7.6
        commands:
          - istioctl
        use_upstream: archive
        uri_a: 'https://github.com/istio/istio/releases/download'
        archive:
          options: '--strip-components=1'
        suffix: tar.gz
      dive:
        version: '0.9.2'
        commands:
          - dive
        use_upstream: archive
        uri_a: 'https://github.com/wagoodman/dive/releases/download'
        archive:
          source_hash: 'fb0b6ee68831fbfc59a06d88638becea09e85da3bb2093a1de4a47ebd4e40296'  # x86_64
          options: '--strip-components=1'
        suffix: tar.gz
      kudo:
        version: '0.17.2'
        name: kubectl-kudo
        commands:
          - kudo
        use_upstream: binary
        uri_b: 'https://github.com/kudobuilder/kudo/releases/download'
        binary:
          source_hash: '8d60af215ba20b992a919a826137a84c709bc8156cc65ff5b908e96edb2d4ad5'
        suffix: tar.gz
      minikube:
        version: '1.16.0-beta.0'
        commands:
          - minikube
        config_file: /etc/default/minikube.ini
        config: {}
        environ_file: /etc/default/minikube.sh
        environ: []
        service: {}
        vm_driver: none
        use_upstream: binary
        uri_b: 'https://github.com/kubernetes/minikube/releases/download'
        binary: {}  # needed
        suffix: null
      stern:
        version: '1.11.0'
        commands:
          - stern
        use_upstream: binary
        uri_b: 'https://github.com/wercker/stern/releases/download'
        binary:
          source_hash: 'e0b39dc26f3a0c7596b2408e4fb8da533352b76aaffdc18c7ad28c833c9eb7db'  # x86_64
        suffix: ''
      kubectx:
        version: '0.9.1'
        commands:
          - kubectx
        use_upstream: archive
        uri_a: 'https://github.com/ahmetb/kubectx/releases/download'
        archive:
          source_hash: 'ce689516f3ae916492bb8f9ee3344da03f6b5a098c1ce2c4a5107b8e9e1cf445'  # x86_64
          options: ''
        suffix: tar.gz
      kubens:
        version: '0.9.1'
        commands:
          - kubens
        use_upstream: archive 
        uri_a: 'https://github.com/ahmetb/kubectx/releases/download'
        archive:
          source_hash: 'dea7839158e4847b8b52709dbfbe9ff2d974df4416b8ea8a86ce4bd622786f52'  # x86_64
          options: ''
        suffix: tar.gz
      cue:
        version: '0.3.0-alpha5'
        commands:
          - cue
        use_upstream: archive
        uri_a: 'https://github.com/cuelang/cue/releases/download'
        archive:
          source_hash: '9d3131e470cdb5182afd9966688f1c052d383145cce005a947156b5591da39b7'  # x86_64
          options: ''
        suffix: tar.gz
      audit2rbac:
        version: '0.8.0'
        commands:
          - audit2rbac
        use_upstream: archive
        uri_a: 'https://github.com/liggitt/audit2rbac/releases/download'
        archive:
          source_hash: '7703cbf3c9c555ea91d4120acf106502fce64c6afdbe1c5aec603a4864560631'  # x86_64
          options: '--strip-components=0'
        suffix: tar.gz

  devlibs:
    wanted:
      - java
      - python
      - csharp
      - javascript
      - kopf
      - k8s
    pkg:
      java:
        name: 'client-java-parent-'
        version: '10.0.0'
        use_upstream: archive
        uri_a: 'https://github.com/kubernetes-client'
        archive:
          source_hash: 'f1cb406f09fb829abd9c48d308d8c208d9df402373761456e1c4ef8bb1d14bad'
          options: '--strip-components=1'
        suffix: tar.gz
      python:
        name: v
        version: '12.0.1'
        use_upstream: archive
        uri_a: 'https://github.com/kubernetes-client'
        archive:
          source_hash: '6d0770a25db9e4e6b4188cf7485c32bef3f0317f729cca19c9af0b6f7d275dc8'
          options: '--strip-components=1'
        suffix: tar.gz
      csharp:
        name: ''
        version: '1.2.0'
        use_upstream: archive
        uri_a: 'https://github.com/kubernetes-client'
        archive:
          source_hash: '0edcefd17f50d0e9d5b34ea318a6a5a13cf9448f918ffa9dec519da9457f9159'
          options: '--strip-components=1'
        suffix: tar.gz
      javascript:
        name: ''
        version: '0.12.1'
        use_upstream: archive
        uri_a: 'https://github.com/kubernetes-client'
        archive:
          source_hash: '60a96ce1c2a1303b7ad750688fb8033e3d6f7bccecfa84158f0eec57ebac4a88'
          options: '--strip-components=1'
        suffix: tar.gz
      kopf:
        name: ''
        version: '0.27'
        use_upstream: archive
        uri_a: 'https://github.com/zalando-incubator/kopf/archive'
        archive:
          source_hash: '25a98ca73b3e7ea8bc38dc31cd5e3f2bd6d443490395166b61eeaeb02d9e1d4d'
          options: '--strip-components=1'
        suffix: tar.gz
      k8s:
        name: v
        version: '1.2.0'
        use_upstream: archive
        uri_a: 'https://github.com/ericchiang/k8s/archive'
        archive:
          source_hash: '18f4c90d7b206d9abb69aff007a534e6cf2e723cbc7d4bb74cc32ec619c418ca'
          options: '--strip-components=1'
        suffix: tar.gz

  operator:
    sdk:
      # https://sdk.operatorframework.io
      rsakey: '0CF50BEE7E4DF6445E08C0EA9AFDE59E90D2B445'
      rsakeyserver: 'keyserver.ubuntu.com'
      wanted:
        - ansible-operator
        - helm-operator
        - operator-sdk
      pkg:
        ansible-operator:
          version: 1.2.0
          use_upstream: binary
          uri_b: 'https://github.com/operator-framework/operator-sdk/releases/download'
          binary: {}  # needed
          commands:
            - ansible-operator
        helm-operator:
          version: 1.2.0
          use_upstream: binary
          uri_b: 'https://github.com/operator-framework/operator-sdk/releases/download'
          binary: {}  # needed
          commands:
            - helm-operator
        operator-sdk:
          version: 1.2.0
          use_upstream: binary
          uri_b: 'https://github.com/operator-framework/operator-sdk/releases/download'
          binary: {}  # needed
          commands:
            - operator-sdk

  operators:
    # https://operatorhub.io
    wanted:
      - grafana-operator
      - prometheus-operator
      - akka-cluster-operator
      - istio-operator
      - shell-operator
    pkg:
      akka-cluster-operator:
        version: 1.0.2
        use_upstream: archive
        uri_a: 'https://github.com/lightbend/akka-cluster-operator/archive'
        archive:
          source_hash: '5df57fe3b25a4c2448ade9225c23e22e3c327c5796eae3bbe1eac168d4ba92a1'
          options: '--strip-components=1'
        suffix: tar.gz
      grafana-operator:
        version: 3.7.0
        use_upstream: archive
        uri_a: 'https://github.com/integr8ly/grafana-operator/archive'
        archive:
          source_hash: '99bdf25e9ef61a5fe4ea6b3cc1d67de242014e97a7239743caf6ac5766a03b30'
          options: '--strip-components=1'
        suffix: tar.gz
      prometheus-operator:
        version: '0.44.1'
        use_upstream: archive
        uri_a: 'https://github.com/coreos/prometheus-operator/archive'
        archive:
          source_hash: 'd935d737ed6ab4b856d69e3c1aeadbd33c3861cd74cc0a84f45e89a57ec846f3'
          options: '--strip-components=1'
        suffix: tar.gz
      istio-operator:
        name: ''
        version: '0.6.5'
        use_upstream: archive
        uri_a: 'https://github.com/banzaicloud/istio-operator/archive'
        archive:
          source_hash: '8bbcf1c201707d9e01f204f3b2a698827b76757a8cdd593de943af64fe1e72d1'
          options: '--strip-components=1'
        suffix: tar.gz
      shell-operator:
        version: '1.0.0-beta.13'
        use_upstream: archive
        uri_a: 'https://github.com/flant/shell-operator/archive'
        archive:
          source_hash: '21aa1863925923f65a0a729f521f9d703ab34450fe726eed93175cd2761362d4'
          options: '--strip-components=1'
        suffix: tar.gz

  server:
    version: '1.20.0'
    config_file: /etc/default/kubernetes-server.ini
    config: {}
    environ_file: /etc/default/kubernetes-server.sh
    environ: []
    service: {}
    pkg:
      name: kubernetes-server
      commands:
        - apiextensions-apiserver
        - kube-scheduler
        - kubeadm
        # kubectl
        - kubelet
        - mounter
        - kube-apiserver
        - kube-controller-manager
        - kube-proxy
      use_upstream: archive
      uri_a: 'https://dl.k8s.io'
      archive:
        options: '--strip-components=2'
        source_hash: 'fb56486a55dbf7dbacb53b1aaa690bae18d33d244c72a1e2dc95fb0fcce45108c44ba79f8fa04f12383801c46813dc33d2d0eb2203035cdce1078871595e446e'  # noqa 204
      suffix: tar.gz

  client:
    version: '1.20.0'
    aliases_file: /etc/default/kubernetes-aliases.sh
    pkg:
      name: kubectl
      commands:
        - kubectl
      use_upstream: archive
      uri_a: 'https://dl.k8s.io'
      uri_b: 'https://storage.googleapis.com/kubernetes-release/release'  # binary
      archive:
        options: '--strip-components=2'
        source_hash: '081472833601aa4fa78e79239f67833aa4efcb4efe714426cd01d4ddf6f36fbf304ef7e1f5373bff0fdff44a845f7560165c093c108bd359b5ab4189f36b1f2f' # noqa 204
      binary:
        name: kubernetes-client
        source_hash: ''
      suffix: tar.gz

  node:
    version: '1.20.0'
    config_file: /etc/default/kubernetes-node.ini
    config: {}
    service: {}
    pkg:
      name: kubernetes-node
      commands: {}
        # kubeadm
        # kubectl
        # kubelet
        # kube-proxy
      use_upstream: archive
      uri_a: 'https://dl.k8s.io'
      archive:
        source_hash: '3e6c90561dd1c27fa1dff6953c503251c36001f7e0f8eff3ec918c74ae2d9aa25917d8ac87d5b4224b8229f620b1830442e6dce3b2a497043f8497eee3705696'  # noqa 204
        options: '--strip-components=2'
      suffix: tar.gz

  k3s:
    version: 'v1.20.0-rc2+k3s1'   # include v in this version
    pkg:
      commands:
        - k3s
      use_upstream: binary
      uri_b: 'https://github.com/rancher/k3s/releases/download'
      uri_s: 'https://get.k3s.io'
      binary:
        source_hash: '44c0d31f86deec3a1d22cc4a56f11b719716863c9664136189342c4845e0cc63'
      script:
        source_hash:
        killall: /usr/local/bin/k3s-killall.sh
        uninstall: /usr/local/bin/k3s-uninstall.sh
        env:
          INSTALL_K3S_BIN_DIR: /usr/local/bin
          INSTALL_K3S_SELINUX_WARN: true
          # INSTALL_K3S_BIN_DIR_READ_ONLY: false
          # INSTALL_K3S_CHANNEL_URL: 'https://update.k3s.io/v1-release/channels'
          # INSTALL_K3S_CHANNEL: stable
          # INSTALL_K3S_EXEC: ''
          # INSTALL_K3S_NAME: ''
          # INSTALL_K3S_SKIP_DOWNLOAD: false
          # INSTALL_K3S_SYMLINK: skip
          # INSTALL_K3S_SKIP_ENABLE: false
          # INSTALL_K3S_SKIP_START: false
          # INSTALL_K3S_SYSTEMD_DIR: /etc/system/systemd
          # INSTALL_K3S_TYPE: ''
          # INSTALL_K3S_VERSION: ''
          # K3S_AGENT_TOKEN: ''
          # K3S_AGENT_TOKEN_FILE: ''
          # K3S_CLUSTER_INIT: ''
          # K3S_CLUSTER_RESET: ''
          # K3S_CLUSTER_SECRET: ''
          # K3S_DATASTORE_ENDPOINT: ''
          # K3S_DATASTORE_CAFILE: ''
          # K3S_DATASTORE_CERTFILE: ''
          # K3S_DATASTORE_KEYFILE:''
          # K3S_KUBECONFIG_MODE: ''
          # K3S_NODE_NAME: ''
          # K3S_RESOLV_CONF: ''
          # K3S_TOKEN: ''
          # K3S_TOKEN_FILE: ''
          # KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      suffix: tar.gz

  identity:
    rootuser: root
    rootgroup: root
  arch: ''
  dir:
    base: /usr/local/
    source: /usr/local/src/k8s/libs/
    operators: /usr/local/src/k8s/operators/
    tmp: /tmp/kubernetes-tmp/
  pkg:
    deps:
      - curl
      - tar
      - gzip
    repo:
      humanname: kubernetes
      name: kubernetes
      comments:
        - installed by salt
      enabled: 1
      gpgcheck: 1
  linux:
    altpriority: 0

  retry_option:
    # https://docs.saltstack.com/en/latest/ref/states/requisites.html#retrying-states
    attempts: 3
    until: true
    interval: 60
    splay: 10

  # Just here for testing
  added_in_defaults: defaults_value
  winner: defaults
