# -*- coding: utf-8 -*-
# vim: ft=yaml
#
# Setup variables using grains['os_family'] based logic.
# You just need to add the key:values for an `os_family` that differ
# from `defaults.yaml`.
# Only add an `os_family` which is/will be supported by the formula
#
# If you do not need to provide defaults via the `os_family` grain,
# you will need to provide at least an empty dict in this file, e.g.
# osfamilymap: {}
---
{%- if grains.os == 'MacOS' %}
    {%- set rootuser = salt['cmd.run']("stat -f '%Su' /dev/console") %}
    {%- set rootgroup = salt['cmd.run']("stat -f '%Sg' /dev/console") %}
{%- elif grains.os == 'Windows' %}
    {%- set rootuser = salt['cmd.run']("id -un") %}
{%- endif %}

Debian:
  pkg:
    repo:
      name: deb https://apt.kubernetes.io/ kubernetes-xenial main
      file: /etc/apt/sources.list.d/kubernetes.list
      key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  devtools:
    pkg:
      minikube:
        use_upstream: binary

RedHat:
  pkg:
    deps:
      - tar
      - gzip
         {%- if grains.os not in ('Amazon',) %}
      - container-selinux
         {%- endif %}
    deps_url:
      - https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm
    repo:
      baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
      gpgkey: 'https://packages.cloud.google.com/yum/doc/yum-key.gpg gpgkey2=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
      repo_gpgcheck: 1

Suse:
  pkg:
    deps:
      - tar
      - gzip

Gentoo: {}

Arch:
  pkg:
    deps:
      - tar
      - gzip
      - which
  linux:
    altpriority: 0

Alpine: {}

FreeBSD:
  identity:
    rootgroup: wheel
  client:
    pkg:
      use_upstream: false
  devtools:
    pkg:
      minikube:
        use_upstream: false

OpenBSD:
  identity:
    rootgroup: wheel
  client:
    pkg:
      use_upstream: false
  devtools:
    pkg:
      minikube:
        use_upstream: archive

Windows:
  div: '\\'
  identity:
    rootuser: {{ rootuser | d('') }}
  dir:
    base: C:\\kubernetes
    source: C:\\kubernetes\src\libs
    operators: C:\\kubernetes\src
    tmp: C:\\temp\kubernetes
  client:
    check: systeminfo
    aliases_file: C:\kubernetes\etc\aliases.sh
    pkg:
      name: kubernetes-cli         # choco
      suffix: ''
      use_upstream: package
      binary:
        options: '--strip-components=2'   # windows
        source_hash: '4c0a27dba1077aaee943e0eb7a787239dd697e1d968e78d1933c1e60b02d5d233d58541d5beec59807a4ffe3351d5152359e11da120bf64cacb3ee29fbc242e6'
  server: {}   # none
  node:
    config_file: C:\kubernetes\etc\node.ini
    pkg:
      use_upstream: archive
      archive:
        options: '--strip-components=3'   # windows
        source_hash: '9d4261af343cc330e6359582f80dbd6efb57d41f882747a94bbf47b4f93292d43dd19a86214d4944d268941622dfbc96847585e6fec15fddc4dbd93d17015fa8'  # noqa 204

  sigs:
    pkg:
      kind:
        binary:
          source_hash: '6f34dbf6f6a9ebdd1d2a2b41a1d7b92d490a53569e45a791f7175c2b4143447f'
      krew:
        use_upstream: binary
        suffix: exe
      kubebuilder:
        use_upstream: false  # no windows binary

  devtools:
    pkg:
      minikube:
        suffix: exe
        config_file: C:\kubernetes\etc\minikube.ini
        environ_file: C:\kubernetes\etc\minkube.sh
        binary:
          source_hash: '36cfbbbe0736aef9c16f8e042943158c926f657d38b61cf1b0fa2a360944ca20'
      devspace:
        name: devspace
        suffix: exe
      octant:
        suffix: zip
        archive:
          source_hash: '15bafbb6354257102c51478dda889eefa7676c60ea291b2756911a5fcb2e1f71'
          options: ''  # zipfile
      k3s:
        use_upstream: false   # no windows binary
      kubectx:
        suffix: zip
        archive:
          source_hash: '50da8ffd2ac9ca7f41c8aa6bf47a7fbd91d17603827b24267b8618fc30e7923f'  # x86_64
          options: ''
      kubens:
        suffix: zip
        archive:
          source_hash: 'bd60e0bd71ef0c0d628dcf09600902e2d67998a29cc5998a404b200fe2d98de8'  # x86_64
          options: ''
      kudo:
        use_upstream: false  # windows not available
      istio:
        suffix: zip
        arch: ''  # noarch
        archive:
          options: ''  # zipfile
      cue:
        suffix: zip
        archive:
          source_hash: '936084adace91705b4e3720d3f54b3a6156d1e2d8662f5bbb1b79fe8afcb2dae'  # x86_64
          options: ''
      audit2rbac:
        archive:
          source_hash: '57e1b6f108141da818eb29ad5755d386f56be067737302fabfa092e335c6ce57'
      stern:
        suffix: exe
        binary:
          source_hash: '75708b9acf6ef0eeffbe1f189402adc0405f1402e6b764f1f5152ca288e3109e'  # amd64
      dive:
        suffix: zip
        archive:
          source_hash: '4e8e48263077f94fccfb1f1c385a95640ef3c7a48fd8ca41cc7e5889ba82da28'  # amd64
          options: ''
      linkerd2:
        name: linkerd2-cli-edge
        suffix: exe
      skaffold:
        suffix: exe

MacOS:
  dir:
    default: /etc/defaults
  identity:
    rootuser: {{ rootuser | d('') }}
    rootgroup: {{ rootgroup | d('') }}
  server: {}
  node: {}
  client:
    aliases_file: /etc/defaults/kubernetes-aliases.sh
    pkg:
      name: kubernetes-cli         # homebrew
      use_upstream: archive
      archive:
        source_hash: '7093a34298297e46bcd1ccb77a9c83ca93b8ccb63ce2099d3d8cd8911ccc384470ac202644843406f031c505a8960d247350a740d683d8910ca70a0b58791a1b'  # noqa 204

  sigs:
    pkg:
      kubebuilder:
        archive:
          source_hash: '39314d45053b6c31eb17e35c9b8d923f8a38277a9a136448345dd4b7f0f308f4'
      kind:
        name: kind      # homebrew
        binary:
          source_hash: '849034ffaea8a0e50f9153078890318d5863bafe01495418ea0ad037b518de90'
      krew:
        commands:
          - krew-darwin_amd64

  devtools:
    pkg:
      minikube:
        check: sysctl -a | grep machdep.cpu.features
        name: minikube               # homebrew
        use_upstream: binary
        binary:
          source_hash: '1ef0ca8ce0aa43f2c7092af173742b597f7876a5e67ab829c5f266dbecdf9469'
      devspace:
        use_upstream: binary
      kudo:
        name: kudo-cli    # homebrew
        tapname: kudobuilder/tap
        binary:
          source_hash: 'df8ca9034ef78000638e9cb08e65c7f054938b4827368755b613a63a8ea8efc7'
      octant:
        suffix: zip
        archive:
          source_hash: 'f3ac074585bd3afbf529da7e37e5e8844150504fdb420f0cc930f31e766ce24a'
          options: '' # zipfile
      linkerd2:
        binary:
          source_hash: '1adc9c53fe968383020b6c4047d42452754e05bc90d1a65f2261d729c6fab4df'
      k3s:
        use_upstream: false   # no macos binary
      kubectx:
        archive:
          source_hash: 'a46c5cf1f6ba8f6aa4dc75fc5a7086d294a28a19cf2fbbf18ac54108a7f713e1'  # x86_64
      kubens:
        archive:
          source_hash: '4ae390ba702d57355d5fb9f2bba04c9b00ae39f740c59044c2d39cd6bfa0ab18'  # x86_64
      cue:
        archive:
          source_hash: '936084adace91705b4e3720d3f54b3a6156d1e2d8662f5bbb1b79fe8afcb2dae'  # x86_64
      stern:
        archive:
          source_hash: '7aea3b6691d47b3fb844dfc402905790665747c1e6c02c5cabdd41994533d7e9'  # x86_64
      dive:
        archive:
          source_hash: '1da3581355d432db38154d80ca9929fc3bca55c473ba286e7869814718f6d578'  # x86_64
      audit2rbac:
        archive:
          source_hash: 'e89d9e7e6e68d7fdf135ab0912f57afda0fea07931ac443a367d35671f83d1b1'
      skaffold:
        binary:
          source_hash: '1e9ad5ed0ba3b277c582dbdb7e13c3307ff1dc21887bf18d4c5aece486e0518c'
